### ISSUE TITLE
How to set a specific tool by default in dwvApp.init()

### ISSUE THREAD

**Issue by Josecongas** [ivmartel/dwv-angular#100]
I have this available tools and _Dwi setup_ in my Angular component:

```
tools = ['Scroll', 'ZoomAndPan', 'WindowLevel', 'Draw'];

  setupDwvApp() {
    this.dwvApp = new dwv.App();
    this.dwvApp.init({
      containerDivId: this.name,
      tools: this.tools,
      shapes: ['Ruler'],
      isMobile: true
    });
  }

```
The thing is that each time I initialize the DwvApp, it is setting by default the first tool of the **_tools_** array  (Scroll) as the selected tool.

Is it possible to manage which tool will be the selected tool at the time that I run the _dwvApp.init()_ function?

**Comment by ivmartel** [comment]
Sorry for taking so long...

This will be possible once I release dwv 0.27. See what I do on the 120-dwv-0-27 branch: [dwv.component.ts#L80](https://github.com/ivmartel/dwv-angular/blob/120-dwv-0-27/src/app/dwv/dwv.component.ts#L80). Initialising the tool is now the responsibility of the client.

**Comment by ivmartel** [comment]
I merged the branch in master and will create a release soon. I hope this solved your problem, closing for now, feel free to comment if you need.
