### ISSUE TITLE
How is canvas getting where the file is ?

### ISSUE THREAD

**Issue by zuesmano** [ivmartel/dwv-angular#118]

**Comment by zuesmano** [comment]
I am confused how or where the file is going when i do add and drop, because i want to call an image from a url. how or where do i pass this the url?

**Comment by ivmartel** [comment]
This comes from dwv, check out (User-Stories#dwv-urs-io-005-data-url-scheme)[https://github.com/ivmartel/dwv/wiki/User-Stories#dwv-urs-io-005-data-url-scheme].

**Comment by zuesmano** [comment]
How can I give it a url? I have read dwv previously but how can i like add a hardcoded url(not encoded url) to this canvas whenever i refresh my page. Like i want to view that hardcoded file. And where can i hardcode this url so whenever i refresh my page, the canvas takes this url and loads it.

**Comment by ivmartel** [comment]
The data url can come from:
* the url of the app, using the `input` argument as in `https://myweb.net/viewer.html?input=path_to_data`
* a url set either programmatically or via a user input (form, drag and drop) and then passed to the app using `app.loadURLs` 

I'm not sure I get your case and if one of these options would suit you...

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
