### ISSUE TITLE
How to Add Folder based upload functionality?

### ISSUE THREAD

**Issue by Code-N-K** [ivmartel/dwv-angular#126]
How to Add Folder based upload functionality like (+) toolkit functionality which exists in JavaScript code but not in Angular Version of dvw. @ivmartel

**Comment by ivmartel** [comment]
You need to add an input field that supports folders (see [caniuse input-file-directory](https://caniuse.com/#feat=input-file-directory)) and then pass the files to the app using `app.loadFiles`.

**Comment by Code-N-K** [comment]
Hi @ivmartel , Hope you are good in spain, as it also got hit with coronavirus.

We are using angular 6 and in need to update the functionality for dwv 26 version for draw lines, add files, folders, URL and Google drive with Dropbox functionality for dicom.

Kindly guide for the same, as angular support is not available in your examples.

Thanks and Regards.

**Comment by ivmartel** [comment]
Thanks, I'm good. Hope all is ok for you too.

I would suggest to have a look at the code of [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile), at least for all the load options. Regarding draw lines there's already some code in the current version, I need to add other shapes, but what is there should give you a good idea. 

I will soon publish a version of dwv-angular that uses dwv 0.27. Adding shapes and other tools will come after.

**Comment by Code-N-K** [comment]
@ivmartel all good here.

In india we are at stage 2 of corona pandemic.

Actually when I tried including dwv package 27, my angular 6 project not getting rendered.

So I need to add options in same dwv 26 version. We need all options for folder based approach which is available in your dwvmobile for angular 6.

One thing more. We have a sample of data which we drag and drop on dwv web at your live URL. But it throws error for slice. But it's working perfectly on desktop based solutions of dicom viewer. 

I could send the sample files if you wanna check.

Thanks and Regards.

**Comment by ivmartel** [comment]
I created #138 for the folder open. Regarding the failing data, can you create another issue and provide the data there. Thanks, closing this one, feel free to comment if you need.

**Comment by Guilherme99** [comment]
I don't undestend. How to add using React class?

**Comment by Guilherme99** [comment]
Could help me?

**Comment by Guilherme99** [comment]
Achieved. Thanks!
