### ISSUE TITLE
https://github.com/ivmartel/dwv/tree/v0.27.0

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv-angular#131]
Is https://github.com/ivmartel/dwv/tree/v0.27.0 available in the latest release of Angular?

**Comment by ivmartel** [comment]
Not yet, I'm working on the finishing touches and should release soon 🤞 !

**Comment by Mamta92** [comment]
Meanwhile can i directly use the dwv.js from  https://github.com/ivmartel/dwv/tree/v0.27.0 and load it in my assets folder?

I'll update the functionalities respectively from Angular code.

**Comment by ivmartel** [comment]
dwv 0.27.0 is also published on npm ([npmjs.com/package/dwv](https://www.npmjs.com/package/dwv)), you can update your `package.json` to get it.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
