### ISSUE TITLE
How to delete an Draw with button click ?

### ISSUE THREAD

**Issue by MounikaAV** [ivmartel/dwv-angular#174]
Hi, 
I am using dwv-angular library in my project.
Here I am not able to delete a draw with a button click. Can someone help me how to achieve this?

Thanks in Advance :)

**Comment by ivmartel** [comment]
There already is a keyboard shortcut: when the draw is selected, press `Supr`.

Key bindings are set there: [dwv.component.ts#L121](https://github.com/ivmartel/dwv-angular/blob/master/src/app/dwv/dwv.component.ts#L121).
They use the default from dwv: `defaultOnKeydown` ([application.js#L759](https://github.com/ivmartel/dwv/blob/v0.27.1/src/app/application.js#L759)) and those defined in tools such as the one defined in the draw tool at [draw.js#L338](https://github.com/ivmartel/dwv/blob/v0.27.1/src/tools/draw.js#L338)

**Comment by MounikaAV** [comment]
Hi,Thanks for reply
But what I meant was **onclick** event in Angular, I want to delete this draw.

**Comment by ivmartel** [comment]
The app does not expose a `deleteDraw(id)` method so it is a bit tricky. Is that what you are looking for? For now, what you can do is get the draw list, remove one and provide it again.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if  you need.
