### ISSUE TITLE
Threshold Undo is not happening after 2 iteration with other tools

### ISSUE THREAD

**Issue by anupzone** [ivmartel/dwv-angular#215]
<img width="755" alt="Screenshot 2021-02-11 at 9 53 04 PM" src="https://user-images.githubusercontent.com/4955675/107665583-98985d00-6cb3-11eb-970b-02213c026e2e.png">
Created project in angular. when using threshold with range slider and going to another tool, and again coming to threshold tool and applying some range then undo is not working.

checked in dwv demo jquery link also here:
https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void

but getting same problem here also.

**Comment by ivmartel** [comment]
Sorry, lost track of this issue. Not sure if it is still valid...

Closing for now, feel free to comment if you need.
