### ISSUE TITLE
project example's Window/Level tool is ineffective

### ISSUE THREAD

**Issue by JoyZhou007** [ivmartel/dwv-angular#223]
i npm start the project ,when i toggle tools to Window/level ，i find it no work  in angular DWV version

**Comment by ivmartel** [comment]
Not sure what is going on, the demo (built from the latest code, see [brainmri](https://ivmartel.github.io/dwv-angular/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void)) works fine for me...

Could you give more context info: what browser are you using, do you see an error in the console log?

**Comment by JoyZhou007** [comment]
> Not sure what is going on, the demo (built from the latest code, see [brainmri](https://ivmartel.github.io/dwv-angular/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void)) works fine for me...
> 
> Could you give more context info: what browser are you using, do you see an error in the console log?
yes, i found that angular-dwv 's online demo's  window/level tool is work, but the project which i clone from the git is not work.
and i also found no error from console log. 
here is my browser version: 88.0.4324.182

**Comment by ivmartel** [comment]
Ok... the latest code is working for me... to be sure that it is not the data, can you try with the 'bbmri' test data of dwv ([tests/data](https://github.com/ivmartel/dwv/tree/develop/tests/data))?

**Comment by JoyZhou007** [comment]
> Ok... the latest code is working for me... to be sure that it is not the data, can you try with the 'bbmri' test data of dwv ([tests/data](https://github.com/ivmartel/dwv/tree/develop/tests/data))?

Hi,i have tried the test data in my local project yet,it is effective.  it proves data is a problem, but why when i import my local file x.jpg or x.dcm in online demo, window/level tool is working? it make me feel so confuse...

**Comment by ivmartel** [comment]
Ah, now I think I get it, window/level is not available for RGB data, being either jpg or dicom data with 'PhotometricInterpretation' different than monochrome. I need to add a check in the code.

**Comment by JoyZhou007** [comment]
> Ah, now I think I get it, window/level is not available for RGB data, being either jpg or dicom data with 'PhotometricInterpretation' different than monochrome. I need to add a check in the code.

Thanks for your help.

**Comment by ivmartel** [comment]
Ok, closing for now, feel free to comment if you need.

**Comment by JoyZhou007** [comment]
> Ah, now I think I get it, window/level is not available for RGB data, being either jpg or dicom data with 'PhotometricInterpretation' different than monochrome. I need to add a check in the code.

Hi,Sir.  i want to ask for if i want to import my local dicom file and using window\level on it,  what i can do in my code ?
by the way, when will you check your code and resolve it?

here is my dicom file , i can't add window\level on it. can you help me to check it, thanks.
[eye.zip](https://github.com/ivmartel/dwv-angular/files/6059310/eye.zip)

**Comment by ivmartel** [comment]
When I say I need to add a check, it is to disable the window/level button for jpg and RGB dicom data. You cannot do window/level on these.

**Comment by JoyZhou007** [comment]
> When I say I need to add a check, it is to disable the window/level button for jpg and RGB dicom data. You cannot do window/level on these.

i got it, thanks

**Comment by ivmartel** [comment]
I created #230 to remove the tool for such data.
