### ISSUE TITLE
How to add an unit for Ruler?

### ISSUE THREAD

**Issue by JoyZhou007** [ivmartel/dwv-angular#224]
i see the DWV demo 's ruler has an unit 'mm',  but in dwv-angular version, ruler only has a number value.

i failed to find the method in DWV document ,so i tried to find method in the source code [https://github.com/ivmartel/dwv/blob/2aeff617def324d078597c0e9bdadfe6674ebae9/src/math/line.js#L227](url) . although i maybe find it, but i  still have no idea about how to resolve my question.

**Comment by ivmartel** [comment]
This got fixed in dwv 0.31 (03/2023): dwv provides an over-ridable function for specific translation for example for units. It does provide a default string, in this case 'mm'.
Closing for now, feel free to comment if you need.
