### ISSUE TITLE
Is it possible to X appear as soon as i select an annotation.

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv-angular#25]
When I select and move an annotation the X appears to delete it, So is it possible to X appear as soon as i select an annotation. Can you please suggest me if this thing is possible and how.

**Comment by ivmartel** [comment]
The behavior was inspired from previous versions of Android, when you want to remove a app from your home screen, To change it you need to modify the dwv code in the draw class starting at [draw.js#L428](https://github.com/ivmartel/dwv/blob/v0.23.4/src/tools/draw.js#L428).

**Comment by ManojSolanki** [comment]
Thanks for the help. I have added konva trash in ShapeEditor and its working now.  

anchor.on('dragmove.edit', function (evt) {          
           // display trash
            var stage = app.getDrawStage();
            var scale = stage.scale();
            var invscale = {'x': 1/scale.x, 'y': 1/scale.y};

            trash.x( stage.offset().x + ( 256 / scale.x ) );
            trash.y( stage.offset().y + ( 20 / scale.y ) );
            trash.scale( invscale );
            let drawLayer = app.getDrawController().getDrawLayer();
            drawLayer.add( trash );
}

**Comment by ivmartel** [comment]
Perfect, can you close the issue?

**Comment by ivmartel** [comment]
Thanks!
