### ISSUE TITLE
Adding JQUI 

### ISSUE THREAD

**Issue by AbdoulazizMaharou** [ivmartel/dwv-angular#3]
Can you add JQUI like this image ? 
![capture](https://user-images.githubusercontent.com/22001590/37802491-f75b05e2-2e2a-11e8-9c85-abb81eb244f4.PNG)

**Comment by ivmartel** [comment]
It is not the purpose of this viewer to integrate JQUI, it should use angular related UI. The demo viewer for JQUI is [dwv-jqui](https://github.com/ivmartel/dwv-jqui).

**Comment by AbdoulazizMaharou** [comment]
Thanks @ivmartel. So when will you add the angular related UI ? I am very interested in that

**Comment by ivmartel** [comment]
The first goal of the demo repos is to show that dwv can be integrated in different frameworks. It's also an example for people to see how the integration can be done. 

My priority is to improve dwv and there is work to do... I'm happy to merge suggestions or to help if you start your own viewer!
