### ISSUE TITLE
Not run in IE 

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv-angular#30]
I have run this project on chrome and its working perfectly. but same when in start in IE nothing is showing even error also not showing. Please help me out.

Thanks

**Comment by ivmartel** [comment]
You are right, the dwv component is missing a call to the browser check that provides missing functions for limited browsers. 

Be aware that performance are not optimal on IE...

**Comment by ManojSolanki** [comment]
Modify pollyfills file and its working now.

**Comment by ivmartel** [comment]
Modifying the `polyfills.ts` file did not work for me, I had to call `dwv.browser.check();` in the component.
