### ISSUE TITLE
Fix dwv drawing integration

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv-angular#4]
Drawings, when integrated as other tools, complains about not being able to access the DrawStage. This must be checked...

**Comment by vaibhavkkulkarni** [comment]
when are you planning to close this ?

**Comment by ivmartel** [comment]
No plans yet, I haven't had much time to look into it... All help is appreciated!

**Comment by ivmartel** [comment]
It was not really broken, just missing some configuration...
