### ISSUE TITLE
How to change the default Measurement Unit

### ISSUE THREAD

**Issue by lakhandewnani** [ivmartel/dwv-angular#41]
We are using DWV module in our project for viewing the diacom images . The measurements which are made on an image could have measurement units like "mm","ms","cm","g" etc . But in DWV module it constraints us to use only one unit as "mm".

The code contained in DWV js file doesn't enables us to change this unit for use. So I am unable to change the unit dynamically for any new measurement taken on the image file.

Please help me to resolve this issue as it is stopping the current functionality of our project.

**Comment by ivmartel** [comment]
Good point. How do you expect to provide the desired unit? I could understand the need for `mm` and `cm` for measurements but I don't see how you could get the other units you mention, could you elaborate?

**Comment by lakhandewnani** [comment]
Hello Team ,

Thanks for the reply .

Let me clear the scenario we are facing at our end .

In our project we are analyzing on any heart issues for our patients , here we have an Intelligence setup working in the back end which analyzes on the dicom images and gives us all the measurements covering the effected sections of the heart . 

These measurements provided by the team can take any unit as "mm" ,"cm","ms" . So In order to show these values in DWV viewer , we need to define the unit of the measurement dynamically which should show the value on the image as per the unit provided.

As if we have a measurement value as 3 cm or 3 mm , this measurement when drawn on the image should show different lengths shapes , which doesn't happens in the current case and it always shows the line using "mm".

Please help us in this scenario and let us know the resolution .

**Comment by lakhandewnani** [comment]
Thanks for your reply .

I took the latest version of our code i.e. 0.24 but the issue with the measurement unit still remains the same. 

Here it seems that while plotting a rectangle shape on the image , we are able to change the measurement unit too , but in our case we are simply drawing a line over the image using Ruler tool which by default forces the measurement unit to be "mm" only.

As you have shown an example of the Rectangle shape , could we in our case use the same concept while drawing a line too and using the "surface" values for defining the unit ? So that if the use the json structure where the "quant" values have "surface " defined in it , would it plot the lines in the desired unit we want ?

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
