### ISSUE TITLE
Received errors during load. Check log for details. Drag and drop more than 3 dcm file

### ISSUE THREAD

**Issue by hasanghanbari** [ivmartel/dwv-angular#432]
this error in demo page
https://ivmartel.github.io/dwv-angular/demo/stable/index.html
how to fixed?

**Comment by ivmartel** [comment]
I tried dragging multiple files (148) and it is working for me, sorry. Could you share the error it gives you?

**Comment by ivmartel** [comment]
There seems to be a collide in your data, are you sure they come from different series? The code has found two files with the same id (`Error: Cannot merge object with same ids`) or at the same position in space (`Error: Zero slice spacing`).

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
