### ISSUE TITLE
Ruler not picking the length in case of my Image

### ISSUE THREAD

**Issue by lakhandewnani** [ivmartel/dwv-angular#45]
Hello Team ,

I am facing an issue where while adding a new annotation on my image using Ruler ,it is not depicting the correct length of the line drawn. It is just displaying me "{length} " keyword . This happens in case of the images used by us only . It works fine with other images .

I have also checked the QuantifyLine method and found that spacing calculated is returned as null when I am using this image .

Please let me know how I could solve this issue . I have attached the image in the zip file .

[Image.zip](https://github.com/ivmartel/dwv-angular/files/2344817/Image.zip)

**Comment by ivmartel** [comment]
Measurements are not available when the DICOM file does not have a `PixelSpacing`. There is no way to guess the size and having a default `1` seems misleading...

The drawing tools could be more intelligent and not propose quantification in that case.

**Comment by ivmartel** [comment]
ivmartel/dwv#641 about image calibration could help. 

Closing for now, feel free to comment if you need.

**Comment by anupzone** [comment]
not getting PixelSpacing then we should hide that because that is not looking good. and double click on label also giving error.
