### ISSUE TITLE
Instructions for how to use `dwv-angular` as a library/component in another app?

### ISSUE THREAD

**Issue by AnalogJ** [ivmartel/dwv-angular#535]
Hey @ivmartel

This DICOM viewer looks great, thanks for all your hard work!

I'm the developer behind [Fasten Health](https://github.com/fastenhealth/fasten-onprem) an open-source personal health record (PHR) system, that allows patients to retrieve and view their medical records from 1000's of healthcare institutions. 

I'd like to [add support for viewing DICOM](https://github.com/fastenhealth/fasten-onprem/issues/39) images in my (Angular 14) app, and [your repo](https://github.com/ivmartel/dwv) was one of the first results that showed up (and seemed to have native Angular support)

Is it possible to use `dwv-angular` as a component in another Angular app? or is it just a stand-alone viewer?

**Comment by ivmartel** [comment]
Thanks! I've mainly used this repo as a demo of what the underlying [dwv](https://github.com/ivmartel/dwv) can do. I'll check how to export the DICOM component of this repo.

Here is a demo of the latest code: [brain mri](https://ivmartel.github.io/dwv-angular/demo/trunk/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void)

**Comment by ivmartel** [comment]
@AnalogJ I've seen that you have made progress with this and that you're using the raw dwv. Do you still need an angular component?

**Comment by AnalogJ** [comment]
Hey @ivmartel 
Yeah, I was able to throw together a working component based on your examples, thanks for that!
 
> Do you still need an angular component?

Honestly, I'm not a frontend developer, and my implementation is pretty hacky and has a couple of broken edge cases. I'd definitely love to use a officially supported Angular component if it was available. 

> don't hesitate if you have any feedback on the lib

Will do. I've been a bit busy working on some new features, but I have a task to write some comprehensive tests for my attachment/document display logic. I'll keep you updated if I notice any weirdness :)

**Comment by ivmartel** [comment]
Please follow #873 for progress. Closing for now, feel free to comment if you need.

**Comment by ivmartel** [comment]
Hi @AnalogJ, #873 is done: dwv-angular is now available as an angular component from npm: https://www.npmjs.com/package/dwv-angular?activeTab=versions (v0.9.0-beta.3). The component uses angular material, I hope this is fine with you. Please tell me how the integration goes and if there is anything that could be improved.
