### ISSUE TITLE
Specify Styles on viewLayer and drawLayer

### ISSUE THREAD

**Issue by gwin003** [ivmartel/dwv-angular#666]
First off, thanks for all your hard work on this library! I'm using the repo as an example to integrate dwv into my application.

Question:
Is there a way to specify styles for the `viewLayer` and `drawLayer` classes? My `viewLayer` and `drawLayer` elements do not have `position: absolute` applied to them like in the demo (likely caused by one of my other packages). This causes them to stack, making my modal in my UI hard to work with because of the blank scroll space where the `drawLayer` lives. 

I've been trying to apply css styles, which I am able to do on the layerGroup element, but I haven't been able to style the `layer` elements at all.

Thanks in advance!

**Comment by ivmartel** [comment]
How do you change the css classes? You mean that updating `dwv.component.scss` does not have any effect?

**Comment by ivmartel** [comment]
I hope you found a solution to your problem. If you can share, that would be cool.

Closing for now, feel free to comment if you need.
