### ISSUE TITLE
How to save json of all lines draw on image and load it with saved json file?

### ISSUE THREAD

**Issue by Code-N-K** [ivmartel/dwv-angular#90]
How to save json of all lines draw on image and load it with saved json file? @ivmartel 

Kindly reply from where can i get all methods for other functionalities.

**Comment by ivmartel** [comment]
Dwv can generate a state file that contains all the drawings. This feature is not yet implemented in the dwv-angular but should not be too hard. 

Check out how it is done in [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile), the gui ([appgui.js#L197](https://github.com/ivmartel/dwv-jqmobile/blob/v0.2.0/src/appgui.js#L197)) has a button that triggers the `app.onStateSave` ([application.js#L1050](https://github.com/ivmartel/dwv/blob/v0.25.2/src/app/application.js#L1050)) and downloads the state file. The state file can be loaded as a regular file.

**Comment by ivmartel** [comment]
It is not in dwv-angular but in the core [dwv](https://github.com/ivmartel/dwv) library.

**Comment by Code-N-K** [comment]
Kindly provide a code details as dwv.onstate is throwing error for state
JSON, as used.

Regards,
Codenk

**Comment by Code-N-K** [comment]
Not able to regenerate this in angular first used this code: in dwv.componnet.ts


this.dwvApp.addEventListener('onStateSave', function ()
    {
      if (this.dwvApp)
      {
        var state = new dwv.State();
        alert(JSON.stringify(state));
        // add href to link (html5)
        var element = self.dwvApp.getElement('download-state');
        var blob = new Blob([state.toJSON(self)], { type: 'application/json' });
        element.href = window.URL.createObjectURL(blob);
      }

    });

saveDraw(): void
  {
    if (this.dwvApp)
    {
      var toggleSaveState = document.createElement("a");
      toggleSaveState.setAttribute("class", "mat-raised-button" + " ");
      toggleSaveState.onclick = this.dwvApp.onStateSave;
      toggleSaveState.download = "state.json";

      alert( "Second:: " + JSON.stringify(toggleSaveState));
    }
    else
    {
      alert("")
    }
  }


Button used:

<button mat-raised-button color="primary" (click)="saveDraw()" [disabled]="!dataLoaded" class="download-state">Save Draw</button>

Kindly Guide.

**Comment by ivmartel** [comment]
dwv-jqmobile use the `download` attribute of an HTML link (see [a#Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes)), not too sure how this would be done in Angular.

**Comment by Code-N-K** [comment]
The big thing i am not able to get the  

var state = new dwv.State();
alert(JSON.stringify(state)); 

this always comes as null.

**Comment by Code-N-K** [comment]
In my below implementation of your code:

in dwv.component.html

<a mat-raised-button color="primary" (click)="saveDraw()" [disabled]="!dataLoaded" class="download-state">Save Draw</a>

now in dwv.component.ts

saveDraw(): void
  {
    if (this.dwvApp)
    {
      this.dwvApp.onStateSave();
   }
}

As defined in the node project dwv.min.js 

i am able to get the blob in new window but, not able to save as file.

Thanks.

**Comment by ivmartel** [comment]
The link needs the `download` flag as in:
```html
<a mat-raised-button color="primary" (click)="saveDraw()" 
  [disabled]="!dataLoaded" class="download-state" download="state.js">Save Draw</a>
```
It also needs to be inside a `div` with the id given at the init of the app for the app the find it.

**Comment by Code-N-K** [comment]
but i want to save this to my database and using this it will be saved at client location. 


Need a workaround so that i can save the associated draw on server.

**Comment by ivmartel** [comment]
Ah, didn't get that. In that case you just need to create the json and send it to your server.
The creation should be something like:
```javascript
var state = new dwv.State();
var json = state.toJSON(dwvApp);
```
where `dwvApp` is the instance of the dwv application.

**Comment by Code-N-K** [comment]
The above statement throws error as state.toJson not a function.

![save issue](https://user-images.githubusercontent.com/21154957/57791015-88a7be00-7759-11e9-8353-142ed6f07cb9.jpg)

**Comment by Code-N-K** [comment]
thanks, it worked and provided me the JSON data.

Kindly also provide details how to get the file name from the url and complete path top open dcm with json file i have used

http://localhost:5000/Doctor/dicomviewer?input=Uploads%2FConsultationImages%2F31%2Fbbmri-53323131.dcm&state=Uploads%2FConsultationImages%2F31%2Fbbmri-53323131.json

where as the jsonloader throws error and if i drag and drop the same json file it shows the annotations but not when using URL.

thanks.

**Comment by ashecret** [comment]
If someone is looking here in the future, to set state from the downloaded JSON file. As per the JQuery solution, read the JSON file and set state as below- 

```
var state = new dwv.State();
state.apply(self, state.fromJSON(jsonData));

**Comment by ivmartel** [comment]
@Code-N-K, regarding your question on the loading of a state from url, the state arguments needs the full path in order to work. It does not need to be encoded.

This url works for me: https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void&state=https://raw.githubusercontent.com/ivmartel/dwv/master/tests/state/v0.3/state-arrow.json

Closing this issue for the release, feel free to comment if you need.
