### ISSUE TITLE
How to call or override dwv onSate, onRedo, onUndo, onToggle

### ISSUE THREAD

**Issue by Code-N-K** [ivmartel/dwv-angular#92]
Kindly provide details onSate, onRedo, onUndo, onToggle can be used in angular so a more use full control can be made.

**Comment by ivmartel** [comment]
For the `onRedo` and `onUndo`, check out how it is done in [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile), the gui ([appgui.js#L185](https://github.com/ivmartel/dwv-jqmobile/blob/v0.2.0/src/appgui.js#L185)) has buttons for it.
I'm not sure what you mean by `onSate` and `onToggle`.

**Comment by Code-N-K** [comment]
I am talking about the toggle information and onRedo, onUndo functionalities of jquery.

![ivmartel](https://user-images.githubusercontent.com/21154957/57767383-d6ef9980-7726-11e9-89d3-4e50658ab4c1.jpg)

The tools and their events 

  redoDraw(): void {
    if (this.dwvApp) {
      this.dwvApp.onRedo();
    }
    else {
      alert("Not Redo");
    }
  }

  undoDraw(): void {
    if (this.dwvApp) {
      this.dwvApp.onUndo();
    }
    else {
      alert("No Undo")
    }
  }

  showInfo(): void {
    if (this.dwvApp) {
      alert("toggle");
      this.dwvApp.toggleInfoLayerDisplay(); //toggleInfoLayerDisplay
    }
    else {
      alert("No Undo")
    }
  }

These events are not working.

**Comment by ivmartel** [comment]
I created two issues: #137 for the toggle and #136 for the undo/redo. Check progress there.
