### ISSUE TITLE
Not able to create 2 instances of the component

### ISSUE THREAD

**Issue by Josecongas** [ivmartel/dwv-angular#99]
My issue happens when I try to create two instances of the **dwv-angular** component. 
The rendering works fine: you can see side by side the two components in the screen with no problem at all. The thing is that the moment you try to drag & drop anything in the second component, it gets received by the first one. No matter in which viewer you drop the DICOMs, they always end up in the first viewer. 

I have been looking through the source code and I am pretty sure that the problem comes with the **dropBox** class that the viewer template have. In the div that has that class is where the logic puts the information of the DICOMs. Having 1 dwv-angular component is the same as having 20: the logic always operates only in the first element of the DOM that has that class. In several parts of the source code the class **dropBox** is hardcoded.

I have tried to fix it and make it dynamic:

- I have put a parameter in the **App()** method, so now it is **App(container)**, being _container_ the div class where I want to put the viewer in. 
- I have replaced all the hardcoded **dropBox** strings by a reference to the **container**.
- Then, in my component I have copied the **dwv-angular** component that you provide, but updated the call to **App()** to now pass the container class (i have two, _drop1_ and _drop2_). This name is received by the component as an input so that it is dynamic.
- Finally, i have added the class name dynamically too in the html template.
- It is generated correctly: I have two divs that have their corresponding classes (the first is _drop1_ and the second is _drop2_). I log the container name sent to **App(container)** and it also is correct.

However, the problem persists: it only applies the logic to the _drop1_ div, the first viewer. 
If the logic was intended to work like this, it is not an Angular component, then: it is not reusable at all. 
I would like to know if you know something about this that might help me. 
Keep the good work going, the **dwv** software is very useful despite of this problem.
Thank you very much.

**Comment by Josecongas** [comment]
SOLVED!

I just found this and applied it to my project:

https://jsfiddle.net/ivmartel/jkcmj0px/

**Comment by ivmartel** [comment]
Nice find! I'm glad it works with angular!
